version: "3"
services: 
  rabbitmq:
    image: rabbitmq:3.11.4
    restart: always
    ports:
     - '5672:5672'
    networks:
     - scc
  logs:
    build:
      context: ./CustomLogs
    environment:
     - LOGS_URI=rabbitmq
    ports: 
     - '8082:8082'
    depends_on:
     - rabbitmq
    networks:
     - scc
  auth: 
    build:
      context: ./Auth
    environment:
     - LOGS_URI=rabbitmq
    ports: 
     - '8081:8081'
    depends_on:
     - rabbitmq
    networks:
     - scc
networks:
  scc: