version: "3"
services: 
  rabbitmq:
    image: rabbitmq:3.11.4
    restart: always
    ports:
     - '5672:5672'
    networks:
     - scc
  gateway: 
    build:
      context: ./APIGateway
    environment:
     - LOGS_URI=rabbitmq
    ports: 
     - '8080:8080'
    depends_on:
     - rabbitmq
    networks:
     - scc
  auth: 
    build:
      context: ./Auth
    environment:
     - LOGS_URI=rabbitmq
    ports: 
     - '8081:8081'
    depends_on:
     - gateway
    networks:
     - scc
  logs:
    build:
      context: ./CustomLogs
    environment:
     - LOGS_URI=rabbitmq
    ports: 
     - '8082:8082'
    depends_on:
     - auth
    networks:
     - scc
  produtos:
    build:
      context: ./Produtos
    environment:
     - LOGS_URI=rabbitmq
    ports: 
     - '8083:8083'
    depends_on:
     - auth
    networks:
     - scc
  ajuda:
    build:
      context: ./Ajuda
    environment:
     - LOGS_URI=rabbitmq
    ports: 
     - '8084:8084'
    depends_on:
     - auth
    networks:
     - scc
  modelacao:
    build:
      context: ./Modelacao
    environment:
     - LOGS_URI=rabbitmq
    ports: 
     - '8085:8085'
    depends_on:
     - auth
    networks:
     - scc
  compras:
    build:
      context: ./Compras
    environment:
     - LOGS_URI=rabbitmq
    ports: 
     - '8086:8086'
    depends_on:
     - auth
    networks:
     - scc
networks:
  scc: